name: rnaseq_atac_pipeline
channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  # Core bioinformatics tools
  - fastqc
  - bowtie2
  - hisat2
  - subread
  - samtools
  - bedtools
  - trim-galore
  - macs2
  - star=2.7.10b

  # Python environment for plotting/data analysis
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn

  # Optional: other helpful tools
  - zlib
  - bzip2
  - lzma
  - curl
  - openjdk=11

  # Pip packages if needed
  - pip:
      - MACS2
